spring:
  docker:
    compose:
      enabled: true
      file: ${COMPOSE_FILE:docker-compose.yml}
      lifecycle-management: start-and-stop

  datasource:
    # 로컬에서 Docker 컨테이너 MySQL에 접속 (root 계정 사용)
    url: jdbc:mysql://localhost:13306/cos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false

  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: yju407@naver.com #네이버 아이디
    password: JYVFH6QBY141 #네이버 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: false
          auth: true
          ssl:
            enable: true #반드시 필요 -> SSL 필요로 되어있으면

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 48efe75b44fe2a4173051596f7cd011f
            client-secret: ${KAKAO_CLIENT_SECRET:}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
          naver:
            client-id: Sxh4tWtKGajFK1MS1zjq
            client-secret: 2as3KpoEeD
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
app:
  email:
    from: yju407@naver.com

file:
  upload-dir: /Users/a/IdeaProjects/Co-s_House/uploads/


server:
  port: 8080

toss:
  payments:
    client-key: test_ck_DLJOpm5QrlOgXm5Qw2xNVPNdxbWn
    secret-key: test_sk_0RnYX2w532oq2Ankz7vMVNeyqApQ
    success-url: http://localhost:8080/payment/success
    fail-url: http://localhost:8080/payment/fail
