spring:
  datasource:
    url: jdbc:mysql://cos-mysql:3306/cos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: cos
    password: cos123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
