spring:
  docker:
    compose:
      enabled: true
      file: ${COMPOSE_FILE:docker-compose.yml}
      lifecycle-management: start-and-stop

#  datasource:
#    # 로컬에서 Docker 컨테이너 MySQL에 접속
#    url: jdbc:mysql://localhost:13306/cos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: root

  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경에서는 update, 운영은 validate 또는 none 추천
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
